### ISSUE TITLE
VIP歌曲播放程序崩溃

### ISSUE THREAD

**Issue by qbmzc** [go-musicfox/go-musicfox#132]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

日推中存在vip歌曲，播放导致程序崩溃

### Environment / 运行环境
```bash
OS: macOS 13.4.1 22F82 arm64 
Terminal: kitty 
CPU: Apple M1
Version: v4.1.2
```
### If applicable, list the error messages you see
如果有错误输出请一并填入

```bash
/us/local/go/src/bufio/bufio.go:144 +0×64
net/http.(*persistConn). readLoop (0x1400067e000)
/us/local/go/src/net/http/transport.go:2093 +0×148
created by net/http. (*Transport) .dialConn
/usr/local/go/src/net/http/transport.go:1750 +0×11 f4
goroutine 204 [select]:
net/http. (*persistConn) .writeLoop (0×1400067e000)
/usr/local/go/src/net/http/transport.go:2392 +0xa4
created by net/http. (*Transport) .dialConn
/usr/local/go/src/net/http/transport.go: 1751 +0×1240
r0
r1
r2
r3
r4
r5
r6
r7
r8
r9
r10
r11
r12
r13
r14
r15
r16
r17
r18
r19
r20
r21
r22
r23
r24
r25
r26
r27
r28
r29 tr sp
fault
0X0
0x0
0x0
0x0
0x183e14647
0×16e621d60
Охбе
0x3
0x688d7e7326b2b0dd
0x688d7e7248d080dd
0x200
Oxb
Oxb
0x1f f800
0x7 fb
0x8f82e824
0×148
0x1e3950£60
0x0
0x6
0x16623000
0×9503
0x16e6230e0
0x600000280dc0
0x0
0x0
0x140005753c8
0x810
0x140004d640
0x16e621ca0
0×183e57c28
0x16e621cb0
0x183e20724
0x183e20724
```
### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

```bash
2023/06/28 16:23:18 find song info :{Quality:ExHigh(2) Id:1882420127}
2023/06/28 16:23:18 search song:问风 金渔
2023/06/28 16:23:23 http.Client.Do fail:Get "http://kuwo.cn/search/list?key=%E9%97%AE%E9%A3%8E%20%E9%87%91%E6%B8%94": net/http: timeout awaiting response headers
2023/06/28 16:23:23 Get "http://kuwo.cn/search/list?key=%E9%97%AE%E9%A3%8E%20%E9%87%91%E6%B8%94": net/http: timeout awaiting response headers
2023/06/28 16:23:23 consumed: 5.230818417s
2023/06/28 16:23:23 {"Id":"1882420127","Size":3427871,"Br":128000,"Url":"http://lv.sycdn.kuwo.cn/405af352e1803a17656b63111b0fe074/649bedfb/resource/30106/trackmedia/M500003a3Cji3QXLwN.mp3?bitrate","Md5":"","Name":"问风","Artist":"金渔","AlbumName":"问风","MatchScore":0.97999996,"Source":"kuwo"}
```

**Comment by qbmzc** [comment]
导致崩溃问题的歌曲
分享金渔的单曲《问风》https://y.music.163.com/m/song?app_version=8.10.15&id=1882420127&textid=1068001&userid=100983702&dlt=0846 (@网易云音乐)

**Comment by anhoder** [comment]
已修复 [commit](https://github.com/go-musicfox/go-musicfox/commit/d4fb743522112b6af578dda2792b350019e68a18)
