### ISSUE TITLE
播放无歌词(猜测)音乐Panic

### ISSUE THREAD

**Issue by sven0219** [go-musicfox/go-musicfox#190]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

我在播放歌单中云盘的音乐时遇到panic，这些歌曲时无歌词的，我猜测是无歌词（从日志也看到lyric相关的报错）的原因，以下是录屏和部份日志：
https://github.com/go-musicfox/go-musicfox/assets/30076203/7d5b88fc-4ef9-48ba-9503-7d1f3112c877

### Environment / 运行环境

laptop info
```
MacOS Ventura 13.5.1
CPU :  Intel
```

musicfox version
```
v4.0.1
```

### If applicable, list the error messages you see
如果有错误输出请一并填入

```
goroutine 60 [select]:
github.com/go-musicfox/go-musicfox/pkg/lyric.(*LRCTimer).Start(0xc0003ee050)
	/go/src/go-musicfox/pkg/lyric/lrc_timer.go:52 +0x1aa
github.com/go-musicfox/go-musicfox/pkg/ui.(*Player).updateLyric.func1()
	/go/src/go-musicfox/pkg/ui/player.go:613 +0x19c
github.com/go-musicfox/go-musicfox/pkg/ui.(*Player).updateLyric(0xc000376000, 0x0?)
	/go/src/go-musicfox/pkg/ui/player.go:636 +0x3ca
created by github.com/go-musicfox/go-musicfox/pkg/ui.(*Player).PlaySong
	/go/src/go-musicfox/pkg/ui/player.go:414 +0x2f9

goroutine 276 [IO wait]:
internal/poll.runtime_pollWait(0x3153cf48, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0001f8180?, 0xc000530000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc0001f8180, {0xc000530000, 0x115a, 0x115a})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0001f8180, {0xc000530000?, 0xc000450a80?, 0xc00053033a?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0000e8000, {0xc000530000?, 0x5?, 0xa?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00043a4b0, {0xc000530000?, 0x0?, 0x8?})
	/usr/local/go/src/crypto/tls/conn.go:784 +0x3d
bytes.(*Buffer).ReadFrom(0xc0002c45f8, {0x493a0a0, 0xc00043a4b0})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0002c4380, {0x2e9640e0?, 0xc0000e8000}, 0xe25?)
	/usr/local/go/src/crypto/tls/conn.go:806 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0002c4380, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:613 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:581
crypto/tls.(*Conn).Read(0xc0002c4380, {0xc00054e000, 0x1000, 0x42b2ee0?})
	/usr/local/go/src/crypto/tls/conn.go:1284 +0x16f
bufio.(*Reader).Read(0xc00031b800, {0xc000540580, 0x9, 0x42cf8a2?})
	/usr/local/go/src/bufio/bufio.go:236 +0x1b4
io.ReadAtLeast({0x4939f20, 0xc00031b800}, {0xc000540580, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:331 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:350
net/http.http2readFrameHeader({0xc000540580?, 0x9?, 0xc0003ba930?}, {0x4939f20?, 0xc00031b800?})
	/usr/local/go/src/net/http/h2_bundle.go:1566 +0x6e
net/http.(*http2Framer).ReadFrame(0xc000540540)
	/usr/local/go/src/net/http/h2_bundle.go:1830 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000303f98)
	/usr/local/go/src/net/http/h2_bundle.go:8815 +0x130
net/http.(*http2ClientConn).readLoop(0xc0000f2600)
	/usr/local/go/src/net/http/h2_bundle.go:8711 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7439 +0xa65
```

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

这是开启debug之后打印的日志
[musicfox.log](https://github.com/go-musicfox/go-musicfox/files/12521453/musicfox.log)

**Comment by anhoder** [comment]
更新版本
