### ISSUE TITLE
鼠标滚轮闪退

### ISSUE THREAD

**Issue by ilyfairy** [go-musicfox/go-musicfox#272]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

在Windows Terminal中, 进入主界面, 随便滚轮一下就会闪退

### Environment / 运行环境

操作系统: Windows 11
终端: Windows Terminal
Musicfox: v4.4.1

### If applicable, list the error messages you see
如果有错误输出请一并填入

```
> musicfox.exe
Caught panic:

caught err: Invalid pointer

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:479 +0x91
panic({0x7ff7ce77f260?, 0xc000306050?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/go-musicfox/go-musicfox/utils.Must(...)
        /go/src/go-musicfox/utils/error.go:9
github.com/go-musicfox/go-musicfox/utils.Must1[...](...)
        /go/src/go-musicfox/utils/error.go:14
github.com/go-musicfox/go-musicfox/internal/remote_control.(*RemoteControl).SetPlayingInfo(0xc0000fc580, {0x0, 0x0, 0x3, 0x55, 0x0, {0x0, 0x0}, {0x0, 0x0}, ...})
        /go/src/go-musicfox/internal/remote_control/remote_control_windows.go:122 +0x7ee
github.com/go-musicfox/go-musicfox/internal/ui.(*Player).DownVolume(0xc00017f860)
        /go/src/go-musicfox/internal/ui/player.go:809 +0x138
github.com/go-musicfox/go-musicfox/internal/ui.(*EventHandler).MouseMsgHandle(0x0?, {0x4e, 0x11, 0x0, 0x0, 0x0, 0x0, 0x5, 0x6}, 0xc0000a6600)
        /go/src/go-musicfox/internal/ui/event_handler.go:399 +0x308
github.com/anhoder/foxful-cli/model.(*Main).mouseMsgHandle(0xc0001e8008, {0x4e, 0x11, 0x0, 0x0, 0x0, 0x0, 0x5, 0x6}, 0xc0000a6600)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:633 +0x103
github.com/anhoder/foxful-cli/model.(*Main).Update(0x3?, {0x7ff7ce84e500?, 0xc000206e40?}, 0xffffffffffffffff?)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:113 +0x26a
github.com/anhoder/foxful-cli/model.(*App).Update(0xc0000a6600, {0x7ff7ce84e500?, 0xc000206e40?})
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:113 +0x40b
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0001ceb60, {0x7ff7ceae9b40?, 0xc0000a6600?}, 0xc00003ac60)
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:412 +0x6f7
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0001ceb60)
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:547 +0x8bc
github.com/anhoder/foxful-cli/model.(*App).Run(0xc0000a6600)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:146 +0x271
github.com/go-musicfox/go-musicfox/internal/commands.runPlayer(0xc000002540?, {0xc00004b620?, 0x0?, 0x0?})
        /go/src/go-musicfox/internal/commands/netease.go:61 +0x605
github.com/gookit/gcli/v2.(*Command).execute(0xc000002480, {0xc00004b620, 0x0, 0x0})
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/cmd.go:243 +0xf6
github.com/gookit/gcli/v2.(*App).doRun(0xc0001ac000, {0x7ff7ce8986eb, 0x7}, {0xc00004b620, 0x0, 0x0})
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:173 +0x413
github.com/gookit/gcli/v2.(*App).Run(0xc0001ac000)
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:126 +0x2e5
main.musicfox()
        /go/src/go-musicfox/cmd/musicfox.go:61 +0x412
github.com/go-musicfox/go-musicfox/internal/runtime.Run(0xc00008c000?)
        /go/src/go-musicfox/internal/runtime/runtime.go:10 +0x33
main.main()
        /go/src/go-musicfox/cmd/musicfox.go:19 +0x1a
```

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
设备不支持调节音量？

**Comment by ilyfairy** [comment]
> 设备不支持调节音量？

其它程序都能调节音量, 也有音频设备, 用的Windows Terminal, 终端应该也没问题

**Comment by anhoder** [comment]
是具体某首歌会触发，还是每首都会

**Comment by ilyfairy** [comment]
> 是具体某首歌会触发，还是每首都会

还没播放歌曲的时候, 新下载的程序, 然后鼠标滚轮滚动就会崩溃

**Comment by anhoder** [comment]
播放之后还会吗

**Comment by ilyfairy** [comment]
播放之后没问题

**Comment by anhoder** [comment]
ok，谢谢回复，下个版本修复
