### ISSUE TITLE
在搜索结果页面添加为下一曲播放时导致程序崩溃

### ISSUE THREAD

**Issue by Yefori-Go** [go-musicfox/go-musicfox#297]
### Check for existing issues
检查是否已存在相同issue

- [x] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

在当前歌单使用搜索功能`/`搜索歌曲时，若当前歌曲在搜索列表中的索引与其在歌单中的实际索引不匹配，按`e`添加为下一曲播放时稳定触发程序崩溃。
<details>

<summary>触发过程记录</summary>

当前页面歌曲：
![当前页面](https://github.com/go-musicfox/go-musicfox/assets/110314400/079efcf0-77bf-40e7-9c27-006ff86f74a8)

搜索：
![image](https://github.com/go-musicfox/go-musicfox/assets/110314400/d6c29bdd-8a23-4726-923f-28ee9e9f2b5f)

搜索结果：
![image](https://github.com/go-musicfox/go-musicfox/assets/110314400/60cf484d-50f9-4edc-9ff4-529780792938)

添加搜索结果列表中索引和播放列表中索引一致歌曲：
![image](https://github.com/go-musicfox/go-musicfox/assets/110314400/3e02e274-ff04-4f46-a8c5-60bf3f75d26a)

添加搜索结果列表中索引和播放列表中索引不一致歌曲：
![image](https://github.com/go-musicfox/go-musicfox/assets/110314400/92f15ad3-c8c1-43fd-aebe-eaa9a514eba8)

</details>

怀疑对象:https://github.com/go-musicfox/go-musicfox/blob/3f72ee40a9ca066618e2088241ec6c85ed0880ff/internal/ui/operate.go#L624
```go
notify.Notify(notify.NotifyContent{
	Title:   notifyTitle,
	Text:    menu.MenuViews()[main.SelectedIndex()].Title,
	Url:     notifyURL,
	GroupId: types.GroupID,
})
```

推测原因：`selectedIndex`为歌曲在歌单中实际索引而非其在搜索结果中索引，引发越界

<details>

<summary>可能的修复方案</summary>
因为没详细看代码，以下内容纯为不负责任推测

```go
notify.Notify(notify.NotifyContent{
	Title:   notifyTitle,
	Text:    menu.MenuViews()[main.SelectedIndex()].Title,
	Url:     notifyURL,
	GroupId: types.GroupID,
})
```
</details>

### Environment / 运行环境

OS: Windows 10 22H2 (10.0.19045) x64
CPU: Intel i5-11400H
musicfox v4.5.3

### If applicable, list the error messages you see
如果有错误输出请一并填入

<details>

<summary>错误输出</summary>

Caught panic:

runtime error: index out of range [14] with length 14

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:479 +0x91
panic({0x7ff7c51734c0?, 0xc00044fc98?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/go-musicfox/go-musicfox/internal/ui.appendSongsToCurPlaylist(0xc000206780, 0x1)
        /go/src/go-musicfox/internal/ui/operate.go:624 +0x82c
github.com/go-musicfox/go-musicfox/internal/ui.(*EventHandler).handle(0xc00006c3b8, {0x7ff7c51e505f, 0xc000131590?})
        /go/src/go-musicfox/internal/ui/event_handler.go:276 +0xc1e
github.com/go-musicfox/go-musicfox/internal/ui.(*EventHandler).KeyMsgHandle(0xc00006c3b8, {0xffffffffffffffff, {0xc00000bebc, 0x1, 0x1}, 0x0, 0x0}, 0x0?)
        /go/src/go-musicfox/internal/ui/event_handler.go:146 +0xba
github.com/anhoder/foxful-cli/model.(*Main).keyMsgHandle(0xc00002c608, {0xffffffffffffffff, {0xc00000bebc, 0x1, 0x1}, 0x0, 0x0}, 0xc00007c9c0)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:569 +0x4e3
github.com/anhoder/foxful-cli/model.(*Main).Update(0xffffffffffffffff?, {0x7ff7c516b500?, 0xc00051e060?}, 0x1?)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:111 +0x2eb
github.com/anhoder/foxful-cli/model.(*App).Update(0xc00007c9c0, {0x7ff7c516b500?, 0xc00051e060?})
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:113 +0x40b
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00020e8f0, {0x7ff7c55651b0?, 0xc00007c9c0?}, 0xc000100ae0)
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:412 +0x6f7
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00020e8f0)
        /go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:547 +0x8bc
github.com/anhoder/foxful-cli/model.(*App).Run(0xc00007c9c0)
        /go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:146 +0x271
github.com/go-musicfox/go-musicfox/internal/commands.runPlayer(0xc000002540?, {0xc0000495e0?, 0x0?, 0x0?})
        /go/src/go-musicfox/internal/commands/netease.go:61 +0x605
github.com/gookit/gcli/v2.(*Command).execute(0xc000002480, {0xc0000495e0, 0x0, 0x0})
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/cmd.go:243 +0xf6
github.com/gookit/gcli/v2.(*App).doRun(0xc0001e2160, {0x7ff7c51d97e8, 0x7}, {0xc0000495e0, 0x0, 0x0})
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:173 +0x413
github.com/gookit/gcli/v2.(*App).Run(0xc0001e2160)
        /go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:126 +0x2e5
main.musicfox()
        /go/src/go-musicfox/cmd/musicfox.go:59 +0x3ee
github.com/go-musicfox/go-musicfox/internal/runtime.Run(0xc000062000?)
        /go/src/go-musicfox/internal/runtime/runtime.go:12 +0x33
main.main()
        /go/src/go-musicfox/cmd/musicfox.go:19 +0x1a

<details>

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

无内容

**Comment by Yefori-Go** [comment]
经测试该修复方案成功修复崩溃，但我的系统中似乎不存在growlnotify（https://github.com/go-musicfox/notificator musicfox在windows下使用的通知方案），所以无法测试该修复是否可以正确发送通知内容。

**Comment by Yefori-Go** [comment]
> 经测试该修复方案成功修复崩溃，但我的系统中似乎不存在growlnotify（https://github.com/go-musicfox/notificator musicfox在windows下使用的通知方案），所以无法测试该修复是否可以正确发送通知内容。

经测试通知内容正确

**Comment by Yefori-Go** [comment]
> 经测试该修复方案成功修复崩溃，但我的系统中似乎不存在growlnotify（https://github.com/go-musicfox/notificator musicfox使用的通知方案），所以无法测试该修复是否可以正确发送通知内容。

经测试通知内容正确
