### ISSUE TITLE
concurrent map writes

### ISSUE THREAD

**Issue by welllog** [go-musicfox/go-musicfox#299]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

播放歌单中的一首歌曲时会固定崩溃，已知该歌曲是vip专属。通过script命令多次抓取屏幕输出，报错截取如下(错误只有一行，然后所有堆栈都会被打印出来)：

记录1:
```
[92m【超燃史诗&节奏电音】游戏/运动/健身/必备 [90m[加载中...][0m                  [0m[0;0Hfatal error: concurrent map writes

goroutine 285 [running]:
net/textproto.MIMEHeader.Set(...)
	/usr/local/go/src/net/textproto/header.go:22
net/http.Header.Set(...)
	/usr/local/go/src/net/http/header.go:40
github.com/cnsilvan/UnblockNeteaseMusic/network.Request(0x1400027ad38)
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/network/network.go:139 +0x804
github.com/cnsilvan/UnblockNeteaseMusic/provider/base.FetchV2({0x140000980e0?, 0x1052f9eae?}, {0x0?, 0x14000010d02?, 0x0?}, 0x1051980cb?, 0x40?)
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/provider/base/base.go:31 +0xb0
github.com/cnsilvan/UnblockNeteaseMusic/provider/migu.(*Migu).GetSongUrl.func1(0x0?, {0x10518fb0a?, 0x14000224140?})
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/provider/migu/migu.go:124 +0x78
created by github.com/cnsilvan/UnblockNeteaseMusic/provider/migu.(*Migu).GetSongUrl in goroutine 277
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/provider/migu/migu.go:122 +0x258
```

记录2:
```
[92m【超燃史诗&节奏电音】游戏/运动/健身/必备 [90m[加载中...][0m                  [0m[0;0Hfatal error: concurrent map iteration and map write

goroutine 489 [running]:
net/http.Header.Clone(...)
	/usr/local/go/src/net/http/header.go:106 
net/http.cloneOrMakeHeader(0x1400022a8d0)
	/usr/local/go/src/net/http/clone.go:69 +0x118
net/http.(*Client).makeHeadersCopier(0x1400022a840, 0x14000524fc0)
	/usr/local/go/src/net/http/client.go:753 +0x30
net/http.(*Client).do(0x1400022a840, 0x14000524fc0)
	/usr/local/go/src/net/http/client.go:611 +0x1ac
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:590
github.com/cnsilvan/UnblockNeteaseMusic/network.Request(0x1400044ad38)
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/network/network.go:147 +0x9f0
github.com/cnsilvan/UnblockNeteaseMusic/provider/base.FetchV2({0x1400028e080?, 0x100979eae?}, {0x0?, 0x14000290286?, 0x0?}, 0x1008180cb?, 0xe0?)
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/provider/base/base.go:31 +0xb0
github.com/cnsilvan/UnblockNeteaseMusic/provider/migu.(*Migu).GetSongUrl.func1(0x0?, {0x10080fb06?, 0x14000230000?})
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/provider/migu/migu.go:124 +0x78
created by github.com/cnsilvan/UnblockNeteaseMusic/provider/migu.(*Migu).GetSongUrl in goroutine 432
	/go/src/go-musicfox/vendor/github.com/cnsilvan/UnblockNeteaseMusic/provider/migu/migu.go:122 +0x258
```

播放曲目：
![711718759300_ pic](https://github.com/go-musicfox/go-musicfox/assets/18400816/30cf8d83-605c-4412-a027-d6abdca6be75)

### Environment / 运行环境

OS: macOS Sonoma 14.5
CPU: Apple M1 Pro
musicfox Version: v4.5.3

### If applicable, list the error messages you see
如果有错误输出请一并填入

[out.txt](https://github.com/user-attachments/files/15894301/out.txt)
[out2.txt](https://github.com/user-attachments/files/15894302/out2.txt)

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
unm先去掉migu

**Comment by welllog** [comment]
OK，去掉这个暂时没发现崩溃了

**Comment by anhoder** [comment]
[v4.5.4](https://github.com/go-musicfox/go-musicfox/releases/tag/v4.5.4)已修复
