### ISSUE TITLE
runtime error: index out of range [83] with length 6

### ISSUE THREAD

**Issue by gythialy** [go-musicfox/go-musicfox#327]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

启动后，按4进入私人FM，一直按下箭头，程序就会崩溃退出

### Environment / 运行环境

MBP 15.1 (24B83)

```
Musicfox - 命令行版网易云音乐

Version: v4.5.6

 ███╗   ███╗ ██╗   ██╗ ███████╗ ██╗  ██████╗ ███████╗  ██████╗  ██╗  ██╗
 ████╗ ████║ ██║   ██║ ██╔════╝ ██║ ██╔════╝ ██╔════╝ ██╔═══██╗ ╚██╗██╔╝
 ██╔████╔██║ ██║   ██║ ███████╗ ██║ ██║      █████╗   ██║   ██║  ╚███╔╝
 ██║╚██╔╝██║ ██║   ██║ ╚════██║ ██║ ██║      ██╔══╝   ██║   ██║  ██╔██╗
 ██║ ╚═╝ ██║ ╚██████╔╝ ███████║ ██║ ╚██████╗ ██║      ╚██████╔╝ ██╔╝ ██╗
 ╚═╝     ╚═╝  ╚═════╝  ╚══════╝ ╚═╝  ╚═════╝ ╚═╝       ╚═════╝  ╚═╝  ╚═╝


```

### If applicable, list the error messages you see
如果有错误输出请一并填入

```
➜ musicfox
Caught panic:

runtime error: index out of range [83] with length 6

Restoring terminal...

goroutine 19 [running, locked to thread]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:479 +0x88
panic({0x1017563c0?, 0x14000686378?})
	/usr/local/go/src/runtime/panic.go:770 +0x124
github.com/go-musicfox/go-musicfox/internal/ui.(*Player).CurSong(0x140000fa000)
	/go/src/go-musicfox/internal/ui/player.go:503 +0xfc
github.com/go-musicfox/go-musicfox/internal/ui.(*Player).songView(0x140000fa000)
	/go/src/go-musicfox/internal/ui/player.go:300 +0x53c
github.com/go-musicfox/go-musicfox/internal/ui.(*Player).View(0x140000fa000, 0x140000a0480, 0x14000390008)
	/go/src/go-musicfox/internal/ui/player.go:198 +0xf0
github.com/anhoder/foxful-cli/model.(*Main).View(0x14000390008, 0x140000a0480)
	/go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:202 +0x534
github.com/anhoder/foxful-cli/model.(*App).View(0x140000a0480?)
	/go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:123 +0x64
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x140000b2ea0, {0x1017ba8a0?, 0x140000a0480?}, 0x14000042600)
	/go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:414 +0x5ec
github.com/charmbracelet/bubbletea.(*Program).Run(0x140000b2ea0)
	/go/src/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:547 +0x6e4
github.com/anhoder/foxful-cli/model.(*App).Run(0x140000a0480)
	/go/src/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:146 +0x25c
github.com/go-musicfox/go-musicfox/internal/commands.runPlayer(0x140000f40c0?, {0x14000032610?, 0x0?, 0x0?})
	/go/src/go-musicfox/internal/commands/netease.go:61 +0x58c
github.com/gookit/gcli/v2.(*Command).execute(0x140000f4000, {0x14000032610, 0x0, 0x0})
	/go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/cmd.go:243 +0xe0
github.com/gookit/gcli/v2.(*App).doRun(0x140000b0000, {0x1012dac0f, 0x7}, {0x14000032610, 0x0, 0x0})
	/go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:173 +0x38c
github.com/gookit/gcli/v2.(*App).Run(0x140000b0000)
	/go/src/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:126 +0x25c
main.musicfox()
	/go/src/go-musicfox/cmd/musicfox.go:59 +0x3ec
github.com/go-musicfox/go-musicfox/internal/runtime.Run.func1.1.1()
	/go/src/go-musicfox/internal/runtime/runtime_darwin.go:24 +0x30
github.com/go-musicfox/go-musicfox/internal/macdriver/core.Autorelease(0x1400015bf60)
	/go/src/go-musicfox/internal/macdriver/core/core.go:80 +0x90
github.com/go-musicfox/go-musicfox/internal/runtime.Run.func1.1()
	/go/src/go-musicfox/internal/runtime/runtime_darwin.go:23 +0x44
github.com/go-musicfox/go-musicfox/utils/errorx.PanicRecoverWrapper(0x0?, 0x0?)
	/go/src/go-musicfox/utils/errorx/recover.go:23 +0x54
created by github.com/go-musicfox/go-musicfox/utils/errorx.Go in goroutine 1
	/go/src/go-musicfox/utils/errorx/recover.go:31 +0x7c

```

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by anhoder** [comment]
v4.5.7已修复
