### ISSUE TITLE
运行时调整窗口大小会导致程序崩溃

### ISSUE THREAD

**Issue by lihaohong6** [go-musicfox/go-musicfox#338]
### Check for existing issues
检查是否已存在相同issue

- [X] Completed/已检查

### Describe the bug and provide steps to reproduce it
描述遇到的bug并提供相应的复现方法

复现：

+ 在设置中设`dynamicMenuRows`为`true`
+ 以小窗口打开任意歌曲数量较多的歌单（大于30），此时每页共显示10首歌
+ 翻到歌单的最后一页
+ 增加终端的高度使每页显示的歌曲数量增加
+ `slice bounds out of range [84:80]`

之前程序默认每页的歌曲数量不变（`start := (m.menuCurPage - 1) * m.menuPageSize`）。一开始每页10首歌的时候，第8页的`start`为70。每页12首歌时，第8页的`start`为84。如果歌单本身只有80首歌，则会导致`slice bounds out of range [84:80]`（见错误输出）。

理想的解决方法是存储当前页面的第一首歌的index，但是写起来比较麻烦。更简单的方法是自动调整当前的页数，如果过高则自动减小。这么做虽然不会崩溃，但是并没有修复一个小问题：用户调整终端高度后页面上的歌曲可能完全不一样。例如，用户在第4页，本来显示的是31-40，改变高度导致每页20首歌之后就显示61-80了。

话说回来，点开歌单并翻页之后再调整窗口高度是用户的问题吧，为什么要这么乱搞（

### Environment / 运行环境

与OS无关。Windows Terminal和Fedora KDE的Konsole下均可以复现。

### If applicable, list the error messages you see
如果有错误输出请一并填入

```
runtime error: slice bounds out of range [84:80]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib64/go/1.23/src/runtime/debug/stack.go:26 +0x6b
runtime/debug.PrintStack()
        /usr/lib64/go/1.23/src/runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/peter/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:479 +0xca
panic({0xfb3ca0?, 0xc000518120?})
        /usr/lib64/go/1.23/src/runtime/panic.go:785 +0x136
github.com/anhoder/foxful-cli/model.(*Main).getCurPageMenus(0xc0003d8008)
        /home/peter/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:565 +0x10b
github.com/anhoder/foxful-cli/model.(*Main).menuListView(0xc0003d8008, 0xc000318ae0, 0xc00004b040)
        /home/peter/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:362 +0x57
github.com/anhoder/foxful-cli/model.(*Main).View(0xc0003d8008, 0xc000318ae0)
        /home/peter/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/main.go:207 +0x1b5
github.com/anhoder/foxful-cli/model.(*App).View(0xc000318ae0)
        /home/peter/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:123 +0xae
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc0003cab60, {0x13317a8, 0xc000318ae0}, 0xc000354a10)
        /home/peter/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:414 +0xc48
github.com/charmbracelet/bubbletea.(*Program).Run(0xc0003cab60)
        /home/peter/go-musicfox/vendor/github.com/charmbracelet/bubbletea/tea.go:547 +0xd29
github.com/anhoder/foxful-cli/model.(*App).Run(0xc000318ae0)
        /home/peter/go-musicfox/vendor/github.com/anhoder/foxful-cli/model/app.go:146 +0x413
github.com/go-musicfox/go-musicfox/internal/commands.runPlayer(0xc000002780, {0xc0003b83f0, 0x0, 0x0})
        /home/peter/go-musicfox/internal/commands/netease.go:62 +0x4ba
github.com/gookit/gcli/v2.(*Command).execute(0xc000002780, {0xc0003b83f0, 0x0, 0x0})
        /home/peter/go-musicfox/vendor/github.com/gookit/gcli/v2/cmd.go:243 +0x18e
github.com/gookit/gcli/v2.(*App).doRun(0xc00039e160, {0x1015291, 0x7}, {0xc0003b83f0, 0x0, 0x0})
        /home/peter/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:173 +0x5b2
github.com/gookit/gcli/v2.(*App).Run(0xc00039e160)
        /home/peter/go-musicfox/vendor/github.com/gookit/gcli/v2/app_run.go:126 +0x405
main.musicfox()
        /home/peter/go-musicfox/cmd/musicfox.go:59 +0x4a5
github.com/go-musicfox/go-musicfox/internal/runtime.Run(0x12d6b80)
        /home/peter/go-musicfox/internal/runtime/runtime.go:12 +0x39
main.main()
        /home/peter/go-musicfox/cmd/musicfox.go:19 +0x1a
```

### If applicable, attach your `${MUSICFOX_ROOT}/musicfox.log` file to this issue.
如果`${MUSICFOX_ROOT}/musicfox.log`里有错误日志，请一并上传

_No response_

**Comment by lihaohong6** [comment]
@anhoder 请问您对这两种解决方案有什么偏好吗？没有的话我就用省事的方法把它修了。

**Comment by anhoder** [comment]
按这个吧：高度变更后，如果打开了dynamicMenuRows，就重算页数并定位到当前页
